/**
 *	MessagePacket Class Declaration
 *	Terrell Ibanez
 *	Encapsulates AutoGenerated Protobuf Class "PPacket"
**/
#ifndef GUARD_MESSAGEPACKET_H
#define GUARD_MESSAGEPACKET_H

//C++ Standard Libraries
#include <memory>
#include <string>

//Protobuf Libraries
#include "PPacket.pb.h"

namespace OnSite {
	class MessagePacket {
		public:
			//Constructor (Outgoing)
			MessagePacket(int fdSocket);

			//TODO Cleanup
			MessagePacket(int fdSocket, std::shared_ptr<OnSite::PPacket> packet);

			//Constructor (Incoming, Parses PPacket from String)
			MessagePacket(int fdSocket, std::string sData);

			//Destructor
			~MessagePacket();
			
			//Serialize for Network Transmission
			std::string serialize();

			//Get Associated Socket
			int getSocket();

			//Get Associated PPacket
			std::shared_ptr<OnSite::PPacket> getPPacket();

		private:
			//Associated Socket File Descriptor
			int fdAssocSocket;
			//Auto-Generated Protobuf class "PPacket"
			std::shared_ptr<OnSite::PPacket> ppPacket;
	};
}
#endif
